name: Push Go image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Boolean button
        required: false
        type: boolean

jobs:
  example_matrix:
      strategy:
        matrix:
          version: [1.17, 1.18, 1.19]
          os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lyovtigranyan619/go_image:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
