name: Pull Go image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Boolean button
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull from DockerHub
        run : docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go_image

      - name: Run container
        run : docker run ${{ secrets.DOCKERHUB_USERNAME }}/go_image:latest
        
