name: Print Hello World With 3 OS

on:
  workflow_dispatch

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-20.04,ubuntu-22.04,]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Create s directory
      run: mkdir my_dir2
    - name: Create a file
      run: touch my_dir2/t2.txt
    - name: Write something in the file
      run: echo "Hello world" > my_dir2/t2.txt
    - name: Check the content
      run: cat my_dir2/t2.txt
