name: Print Hello World

on:
  workflow_dispatch

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04,ubuntu-21.04,ubuntu-22.04,]
  build:
    runs-on: ${{ matrix.os}}
    steps:
      - name: Create s directory
        run: mkdir my_dir
      - name: Create a file
        run: touch my_dir/t.txt
      - name: Write something in the file
        run: echo "Hello world" > my_dir/t.txt
      - name: Check the content
        run: cat my_dir/t.txt
